 <?php
 
require_once ('config.php' );
$options = array('location' => 'http://ipccfscenter.com/TPSServices/server_jav.php', 
                  'uri' => 'http://ipccfscenter.com/');
$api = new SoapClient(NULL, $options);
$fstream='<?xml version="1.0" encoding="UTF-8" ?>
<DOCUMENT xmlns="UploadCustomerData.xsd">
<CDM>
<CUSTOMER_ID_SEQ></CUSTOMER_ID_SEQ>
<CUSTOMER_ID>090909</CUSTOMER_ID>
<CUSTOMER_LABEL></CUSTOMER_LABEL>
<NAME>TANTO BERSAMA</NAME>
<ADDRESS></ADDRESS>
<NPWP></NPWP>
<EMAIL></EMAIL>
<WEBSITE></WEBSITE>
<PHONE></PHONE>
<COMPANY_TYPE></COMPANY_TYPE>
<ALT_NAME></ALT_NAME>
<DEED_ESTABLISHMENT></DEED_ESTABLISHMENT>
<CUSTOMER_GROUP></CUSTOMER_GROUP>
<CUSTOMER_TYPE></CUSTOMER_TYPE>
<SVC_VESSEL></SVC_VESSEL>
<SVC_CARGO></SVC_CARGO>
<SVC_CONTAINER></SVC_CONTAINER>
<SVC_MISC></SVC_MISC>
<IS_SUBSIDIARY></IS_SUBSIDIARY>
<HOLDING_NAME></HOLDING_NAME>
<EMPLOYEE_COUNT></EMPLOYEE_COUNT>
<IS_MAIN_BRANCH></IS_MAIN_BRANCH>
<PARTNERSHIP_DATE></PARTNERSHIP_DATE>
<PROVINCE></PROVINCE>
<CITY></CITY>
<CITY_TYPE></CITY_TYPE>
<KECAMATAN></KECAMATAN>
<KELURAHAN></KELURAHAN>
<POSTAL_CODE></POSTAL_CODE>
<FAX></FAX>
<PARENT_ID></PARENT_ID>
<CREATE_BY></CREATE_BY>
<CREATE_DATE></CREATE_DATE>
<CREATE_VIA></CREATE_VIA>
<CREATE_IP></CREATE_IP>
<EDIT_BY></EDIT_BY>
<EDIT_DATE></EDIT_DATE>
<EDIT_VIA></EDIT_VIA>
<EDIT_IP></EDIT_IP>
<IS_SHIPPING_AGENT></IS_SHIPPING_AGENT>
<IS_SHIPPING_LINE></IS_SHIPPING_LINE>
<REG_TYPE></REG_TYPE>
<IS_PBM></IS_PBM>
<IS_FF></IS_FF>
<IS_EMKL></IS_EMKL>
<IS_PPJK></IS_PPJK>
<IS_CONSIGNEE></IS_CONSIGNEE>
<REGISTRATION_COMPANY_ID></REGISTRATION_COMPANY_ID>
<HEADQUARTERS_ID></HEADQUARTERS_ID>
<HEADQUARTERS_NAME></HEADQUARTERS_NAME>
<STATUS_APPROVAL></STATUS_APPROVAL>
<TYPE_APPROVAL></TYPE_APPROVAL>
<STATUS_CUSTOMER></STATUS_CUSTOMER>
<CONFIRM_DATE></CONFIRM_DATE>
<APPROVE_DATE></APPROVE_DATE>
<ACCEPTANCE_DOC></ACCEPTANCE_DOC>
<ACCEPTANCE_DOC_DATE></ACCEPTANCE_DOC_DATE>
<REJECT_NOTES></REJECT_NOTES>
<REJECT_USER></REJECT_USER>
<REJECT_DATE></REJECT_DATE>
<BRANCH_SIGN></BRANCH_SIGN>
<PASSPORT></PASSPORT>
<CITIZENSHIP></CITIZENSHIP>
</CDM>
</DOCUMENT>
';
echo $api->CheckConnection('null');//http://10.1.6.112/cfs-center/TPSServices/WsGetLCL.php
//echo $api->UploadMohonPLP($fStream,MTI,MTIPYG);http://10.1.6.112/cfs-center/TPSServices/ReadUploadMohonPLP.php
//echo $api->GetResponPLP(PLDC,PLDC,PLDC);//http://10.1.6.112/cfs-center/TPSServices/ReadGetResponPLP_Asal.php
//echo $api->GetResponPLP_Tujuan(PLDC,PLDC,PLDC);//http://10.1.6.112/cfs-center/TPSServices/ReadGetResponPLP_Tujuan.php
//echo $api->UploadBatalPLP($fStream,MTI,MTIPYG);http://10.1.6.112/cfs-center/TPSServices/ReadUploadBatalPLP.php
//echo $api->GetResponBatalPLP_Asal(PLDC,PLDC,PLDC);http://10.1.6.112/cfs-center/TPSServices/ReadGetResponBatalPLP_Asal.php
//echo $api->GetResponPLP_Tujuan(PLDC,PLDC,PLDC);http://10.1.6.112/cfs-center/TPSServices/ReadGetResponBatalPLP_Tujuan.php
/* $TES = '<?xml version="1.0" encoding="UTF-8" ?><DOCUMENT xmlns=" loadbatalplp.xsd">
<BATALPLP>
<HEADER>
<KD_KANTOR>040300</KD_KANTOR>
<TIPE_DATA>2<TIPE_DATA>
<KD_TPS>KOJA</KD_TPS >
<REF_NUMBER>000030303</REF_NUMBER>
<NO_SURAT>NPCT1/PLP-OBC/2017/0712/2898</NO_SURAT>
<TGL_SURAT>20170728</TGL_SURAT>
<NO_PLP>PLP001</NO_PLP>
<TGL_PLP></TGL_PLP>
<ALASAN></ALASAN>
<NO_BC11>12</NO_BC11>
<TGL_BC11>23</TGL_BC11>
<NM_PEMOHON>PT TOYOTA</NM_PEMOHON>
</HEADER>
<DETIL>
<CONT>
<NO_CONT>CONT093</NO_CONT>
<UK_CONT>20</UK_CONT>
</CONT>
</DETIL>
</BATALPLP>
</DOCUMENT>';
echo $api->UploadBatalPLP($TES,PLDC,PLDC);
 */
/* function incrementalHash($len,$char){
  $charset = ($char==0)?"0123456789":"ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  $base = strlen($charset);
  $result = '';

  $now = explode(' ', microtime())[1];
  while ($now >= $base){
    $i = $now % $base;
    $result = $charset[$i] . $result;
    $now /= $base;
  }
  return substr($result, -$len);
}

for($i=0;$i<10;$i++){
$detil = ($i%2==0) ? '<CONT><NO_CONT>'.incrementalHash(4,1).incrementalHash(7,0).'</NO_CONT><UK_CONT>40</UK_CONT></CONT>' : '<KMS><JNS_KMS>'.incrementalHash(2,0).'</JNS_KMS><JML_KMS>120</JML_KMS><NO_BL_AWB>'.incrementalHash(6,1).incrementalHash(6,0).'</NO_BL_AWB><TGL_BL_AWB>20160602</TGL_BL_AWB></KMS>';*/
/* $fStream = '<?xml version="1.0" encoding="UTF-8"?><DOCUMENT xmlns="loadplp.xsd"><LOADPLP><HEADER><KD_KANTOR>040300</KD_KANTOR><TIPE_DATA>1</TIPE_DATA><KD_TPS_ASAL>NCT1</KD_TPS_ASAL><REF_NUMBER>'.incrementalHash(4,1).date('Ymd').str_pad($i,6,"0",STR_PAD_LEFT).'</REF_NUMBER><NO_SURAT>NPCT1/PLP-OBC/2017/0712/2898</NO_SURAT><TGL_SURAT>20170713</TGL_SURAT><GUDANG_ASAL>NCT1</GUDANG_ASAL><KD_TPS_TUJUAN>MTI0</KD_TPS_TUJUAN><GUDANG_TUJUAN>BAND</GUDANG_TUJUAN><KD_ALASAN_PLP>2</KD_ALASAN_PLP><YOR_ASAL>38</YOR_ASAL><YOR_TUJUAN>26</YOR_TUJUAN><CALL_SIGN>DDSC2</CALL_SIGN><NM_ANGKUT>GLASGOW EXPRESS</NM_ANGKUT><NO_VOY_FLIGHT>037S</NO_VOY_FLIGHT><TGL_TIBA>20170623</TGL_TIBA><NO_BC11>002696</NO_BC11><TGL_BC11>20170623</TGL_BC11><NM_PEMOHON>SUMARDI</NM_PEMOHON></HEADER><DETIL>'.$detil.'</DETIL></LOADPLP></DOCUMENT>';
 */
 
/* $fstream='<?xml version="1.0" encoding="UTF-8"?><DOCUMENT xmlns="loadplp.xsd"><LOADPLP><HEADER><KD_KANTOR>040300</KD_KANTOR><TIPE_DATA>1</TIPE_DATA><KD_TPS_ASAL>PLDC</KD_TPS_ASAL><REF_NUMBER>170728000101406</REF_NUMBER><NO_SURAT>899/PLP/GM.III/PTP-17</NO_SURAT><TGL_SURAT>20170728</TGL_SURAT><GUDANG_ASAL>TER3</GUDANG_ASAL><KD_TPS_TUJUAN>RAYA</KD_TPS_TUJUAN><GUDANG_TUJUAN>RAYA</GUDANG_TUJUAN><KD_ALASAN_PLP>2</KD_ALASAN_PLP><YOR_ASAL>47</YOR_ASAL><YOR_TUJUAN>45</YOR_TUJUAN><CALL_SIGN>N/A</CALL_SIGN><NM_ANGKUT>IRENES RELIANCE</NM_ANGKUT><NO_VOY_FLIGHT>708A</NO_VOY_FLIGHT><TGL_TIBA>20170726</TGL_TIBA><NO_BC11>003129</NO_BC11><TGL_BC11>20170726</TGL_BC11><NM_PEMOHON>SARKANI</NM_PEMOHON></HEADER><DETIL><CONT><NO_CONT>MAEU6729574</NO_CONT><UK_CONT>20</UK_CONT></CONT></DETIL></LOADPLP></DOCUMENT>';
echo $api->UploadMohonPLP($fStream,TEST,TEST);
 */
 //}
#echo $api->UploadBatalPLP($fStream,MTI,MTIPYG);
 ?>